fail_fast: true
repos:

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
  - id: codespell
    args:
      - --skip=*.lock,tests/test_class_oelint_vars_misspell.py,oelint_adv/data/*
      # Provide a comma separated list of ignored words here:
      - -L=mispell
