#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.nomkdir"
TESTOCC="2"
cat > ${TESTFILE} << EOF
do_install() {
    mkdir -p /tmp/sjdsdasjdha
}
do_install_append() {
    mkdir -p /tmp/sjdsdasjdha
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1