#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
TESTPATCHFOLDER="${TMP}files"
trap "rm -f ${TESTFILE} && rm -rf ${TESTPATCHFOLDER}" EXIT
TESTID="oelint.file.patchsignedoff"
TESTOCC="1"
cat > ${TESTFILE} << EOF
SRC_URI = "file://test.patch"
EOF
mkdir -p ${TESTPATCHFOLDER}
cat > ${TESTPATCHFOLDER}/test.patch << EOF
This is not a patch
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1