#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.func.machinespecific"
TESTOCC="0"
cat > ${TESTFILE} << EOF
COMPATIBLE_MACHINE = "foo"
COMPATIBLE_MACHINE += "|bar"
do_install_append_fooarch() {
    abc
}
do_configure_append_bararch() {
    abc
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1