#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pnusagediscouraged"
TESTOCC="0"
cat > ${TESTFILE} << EOF
HOMEPAGE = "http://abc.com"
BUGTRACKER = "http://\${FOO}.com"
SUMMARY = "Someother string"
DESCRIPTION = "1"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1