#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.doublemodify"
TESTOCC="9"
cat > ${TESTFILE} << EOF
A_append_prepend_remove += "1"
A_append_prepend += "1"
A_append += "1"
A_prepend_remove += "1"
A_append_remove += "1"
A_remove += "1"
A_append_prepend_remove = " 1 "
A_append_remove = " 1 "
A_prepend_remove = " 1 "
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1