#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.pythonprefix"
TESTOCC="0"
cat > ${TESTFILE} << EOF
do_foo() {
    mkdir -p /tmp/sjdsdasjdha
    ./configure
}
python do_bar() {
    import os
    print("fooooooo!!!!")
}
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1