#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.heredocs"
TESTOCC="2"
cat > ${TESTFILE} << EOF
do_foo() {
    cat    >  \${T}/some.files <<   abchhehdhhe
    kfkdfkd
    abchhehdhhe
}
do_install_append() {
    cat    <<   EOF    >\${T}/some.files
    abc
    EOF
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1