#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.func.machinespecific"
TESTOCC="0"
cat > ${TESTFILE} << EOF
COMPATIBLE_MACHINE = "foo"
COMPATIBLE_MACHINE += "|bar"
do_install_append_fooarch() {
    abc
}
do_configure_append_bararch() {
    abc
}
do_install_ptest () {
 	cp -r \${B}/testsuite \${D}\${PTEST_PATH}/
 	cp \${B}/.config      \${D}\${PTEST_PATH}/
 	ln -s /bin/busybox   \${D}\${PTEST_PATH}/busybox
}
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1