#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
TESTFILEINC="/tmp/oelint_adv_test.inc"
trap "rm -f ${TESTFILE} && rm -f ${TESTFILEINC}" EXIT
TESTID="oelint.file.includenotfound"
TESTOCC="1"
# cat > ${TESTFILEINC} << EOF
# VAR = "a"
# EOF
cat > ${TESTFILE} << EOF
include oelint_adv_test.inc
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1