#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.appendop"
TESTOCC="0"
cat > ${TESTFILE} << EOF
A ??= "1"
A_append = "2"

B_append = "B"
B ?= "A"

C ??= "1"
C_append = "2"

D_append = "2"
D ?= "1"

F ??= "1"
F_prepend = "2"

G_prepend = "B"
G ?= "A"

H ??= "1"
H_prepend = "2"

I_prepend = "2"
I ?= "1"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1