#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pkgspecific"
TESTOCC="12"
cat > ${TESTFILE} << EOF
RDEPENDS = "foo"
RRECOMMENDS = "foo"
RSUGGESTS = "foo"
RCONFLICTS = "foo"
RPROVIDES = "foo"
RREPLACES = "foo"
FILES = "foo"
pkg_preinst = "foo"
pkg_postinst = "foo"
pkg_prerm = "foo"
pkg_postrm = "foo"
ALLOW_EMPTY = "foo"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1