#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.nopythonprefix"
TESTOCC="1"
cat > ${TESTFILE} << EOF
python do_foo() {
    mkdir -p /tmp/sjdsdasjdha
    ./configure
}
python do_bar() {
    import os
    print("fooooooo!!!!")
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1