#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.filessetting.double"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SPLITPKGS = "\${PN}-ping \${PN}-arping \${PN}-tracepath \${PN}-clockdiff \${PN}-tftpd \${PN}-rdisc \
             \${@bb.utils.contains('PACKAGECONFIG', 'rarpd', '\${PN}-rarpd', '', d)} \
             \${@bb.utils.contains('DISTRO_FEATURES', 'ipv6', '\${PN}-traceroute6 \${PN}-ninfod', '', d)}"
PACKAGES += "\${SPLITPKGS}"

ALLOW_EMPTY_\${PN} = "1"
RDEPENDS_\${PN} += "\${SPLITPKGS}"

FILES_\${PN} = ""
FILES_\${PN}-ping = "\${base_bindir}/ping.\${BPN}"
FILES_\${PN}-arping = "\${base_bindir}/arping"
FILES_\${PN}-tracepath = "\${base_bindir}/tracepath"
FILES_\${PN}-traceroute6	= "\${base_bindir}/traceroute6"
FILES_\${PN}-clockdiff = "\${base_bindir}/clockdiff"
FILES_\${PN}-tftpd = "\${bindir} \${base_bindir}/tftpd"
FILES_\${PN}-rarpd = "\${base_sbindir}/rarpd  \${systemd_unitdir}/system/rarpd@.service"
FILES_\${PN}-rdisc = "\${base_sbindir}/rdisc"
FILES_\${PN}-ninfod = "\${base_sbindir}/ninfod \${sysconfdir}/init.d/ninfod.sh"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1