#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.order.*"
TESTOCC="0"
cat > ${TESTFILE} << EOF
do_fetch() {
    :
}
do_unpack() {
    :
}
do_patch() {
    :
}
do_configure() {
    :
}
do_compile() {
    :
}
do_install() {
    :
}
do_populate_sysroot() {
    :
}
do_package() {
    :
}
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1