#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
TESTPATCHFOLDER="/tmp/files"
trap "rm -f ${TESTFILE} && rm -rf ${TESTPATCHFOLDER}" EXIT
TESTID="oelint.file.patchsignedoff"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://test.patch"
EOF
mkdir -p ${TESTPATCHFOLDER}
cat > ${TESTPATCHFOLDER}/test.patch << EOF
Signed-off-by: "some body <some@body.com>"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1