#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
TESTPATCHFOLDER="/tmp"
trap "rm -f ${TESTFILE} && rm ${TESTPATCHFOLDER}/abc.inc" EXIT
TESTID="oelint.var.multiinclude"
TESTOCC="1"
cat > ${TESTFILE} << EOF
include abc.inc
B = "2"
include abc.inc
EOF
mkdir -p ${TESTPATCHFOLDER}
cat > ${TESTPATCHFOLDER}/abc.inc << EOF
A = "1"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1