#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.srcurisrcrevtag"
TESTOCC="2"
cat > ${TESTFILE} << EOF
SRC_URI += "git://foo.org/gaz.git;tag=${PV};name=foo"
SRCREV_foo = "1234"

SRC_URI += "git://foo.org/gaz.git;tag=${PV};name=abc"
SRCREV_bar = "1234"

SRC_URI += "git://foo.org/gaz.git;tag=${PV}"
SRCREV = "1234"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1