#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.addnotaskbody"
TESTOCC="3"
cat > ${TESTFILE} << EOF
do_foo() {

}
addtask do_foo

addtask do_notexists

addtask foo
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1