#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.docstrings"
TESTOCC="0"
cat > ${TESTFILE} << EOF
do_foo() {
    :
}
addtask do_foo
do_foo[doc] = "Fooo!!!!"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1