#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bbappend"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.append.protvars.*"
TESTOCC="0"
cat > ${TESTFILE} << EOF
PV ?= "sdlsdsd"
PR ?= "sdsd"
SRCREV ?= "ksdhdhkdhk"
LICENSE ?= "CLOSED"
LIC_FILES_CHKSUM ?= "skddskda"
PV ??= "sdlsdsd"
PR ??= "sdsd"
SRCREV ??= "ksdhdhkdhk"
LICENSE ??= "CLOSED"
LIC_FILES_CHKSUM ??= "skddskda"
SRC_URI += "file://foo.patch"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1