#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pbpusage"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://\${BP}.patch \
           git://\${BP}.com/\${BP}.git \
           https://foo.org/\${BP} \
           git://foo.org/bar.git;name=\${P}"
SRCREV_${P} = "01234567890abcdef"
S = "${WORDKIR}/${BP}"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1