#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.spacesassignment"
TESTOCC="0"
cat > ${TESTFILE} << EOF
A = "a"
PACKAGECONFIG[system-pcre] = "-Dinternal_pcre=false,-Dinternal_pcre=true,libpcre"
SRC_URI[a-b-c.md5sum] = "a95c4a842325689cad729e9ca1906233"
SRC_URI[a-b-c.sha256sum] = "35dacbd4d39cb32fd7ec505c9823451dfd5b94dbb59f3ed146e7d361fcec3505"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1