#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pathhardcode.*"
TESTOCC="0"
cat > ${TESTFILE} << EOF
VAR = "${systemd_user_unitdir}"
VAR = "${systemd_system_unitdir}"
VAR = "${docdir}"
VAR = "${infodir}"
VAR = "${mandir}"
VAR = "${libexecdir}"
VAR = "${systemd_unitdir}"
VAR = "${libdir}"
VAR = "${bindir}"
VAR = "${datadir}"
VAR = "${includedir}"
VAR = "${localstatedir}"
VAR = "${nonarch_base_libdir}"
VAR = "${nonarch_libdir}"
VAR = "${oldincludedir}"
VAR = "${sbindir}"
VAR = "${servicedir}"
VAR = "${sharedstatedir}"
VAR = "${sysconfdir}"
VAR = "/some/other/dir/${sysconfdir}"
SUMMARY = "/usr/datadir"
DESCRIPTION = "/usr/datadir"
HOMEPAGE = "/usr/datadir"
AUTHOR = "/usr/datadir"
BUGTRACKER = "/usr/datadir"
# Here we can talk freely about /usr/lib and /usr/bin
FILES_${PN} += "/usr/lib/totally.valid.file"
do_install_append() {
    #To remove the default files from /etc/somefolder
    rm -f \${D}\${sysconfdir}/somefolder/*
    install -m 0644 \${S}/usr/lib/* \${D}${libdir}
    install -m 0644 \${WORKDIR}/usr/bin \${D}${bindir}
    echo "foo" | sed "s#/usr/bin/python#/usr/bin/env python#g" > ${D}${bindir}/foo
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1