#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.pythonprefix"
TESTOCC="1"
cat > ${TESTFILE} << EOF
do_foo() {
    mkdir -p /tmp/sjdsdasjdha
    ./configure
}
do_bar() {
    import os
    bb.warn("dsjkdjdsdjk")
}
do_configure() {
    oe_runconf
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1