#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.homepageprefix"
TESTOCC="0"
cat > ${TESTFILE} << EOF
HOMEPAGE = "http://fancy.org"
HOMEPAGE = "https://fancy.org"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1