#!/bin/sh
TESTFILE="/tmp/oelint_adv_test-native.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.nativefilename"
TESTOCC="0"
cat > ${TESTFILE} << EOF
inherit native
A = "1"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1