#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.srcuridomains"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI += "git://abc.group.com/a.git"
SRC_URI += "ftp://abc.group.com/some.patch"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1