#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.srcurioptions"
TESTOCC="22"
cat > ${TESTFILE} << EOF
SRC_URI += "abc://foo"
SRC_URI += "file://foo;notexists=true"
SRC_URI += "file://foo;protocol=false"
SRC_URI += "bzr://foo;tag=bzr"
SRC_URI += "crcc://foo;localdir=foo"
SRC_URI += "cvs://foo;downloadfilename=123456"
SRC_URI += "ftp://foo;nocheckout=foo"
SRC_URI += "git://foo;proto=foo"
SRC_URI += "gitsm://foo;proto=foo"
SRC_URI += "gitannex://foo;notexist=true"
SRC_URI += "hg://foo;downloadfilename=foo"
SRC_URI += "http://foo;protocol=true"
SRC_URI += "https://foo;protocol=true"
SRC_URI += "osc://foo;downloadfilename=foo"
SRC_URI += "p4://foo;downloadfilename=foo"
SRC_URI += "repo://foo;downloadfilename=foo"
SRC_URI += "ssh://foo;downloadfilename=true"
SRC_URI += "s3://foo;tag=true"
SRC_URI += "sftp://foo;tag=true"
SRC_URI += "npm://foo;tag=foo"
SRC_URI += "npmsw://foo;tag=foo"
SRC_URI += "svn://foo;downloadfilename=foo"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1