#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.licenseremotefile"
TESTOCC="0"
cat > ${TESTFILE} << EOF
LIC_FILES_CHKSUM = "file://LICENSE;md5=sjdjasdjhddh"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1