#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.valuequoted"
TESTOCC="0"
cat > ${TESTFILE} << EOF
A = "a"
A += "b"
PACKAGECONFIG[foo] = "-DFOO=ON,-DFOO=OFF,"
EXTRA_OECMAKE += "\
    -DBUILD_TESTS=OFF \
"
DEPENDS += "\
 a \
 b \ 
 c \
"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1