#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.mispell"
TESTOCC="0"
cat > ${TESTFILE} << EOF
RDEPENDS_\${PN} = "foo"
PACKAGECONFIG[foo] = "a"
GOPATH = "abc"
PACKAGECONFIG_A = "a"
PACKAGECONFIG_B = "c"

PACKAGES += "\${PN}-foo"

do_configure() {
    ./configure \${PACKAGECONFIG_A}
}

python do_foo() {
    d.getVar("PACKAGECONFIG_B")
}

INITSCRIPT_PARAMS_\${PN}-foo = "bar"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1