#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.customorder"
TESTOCC="1"
cat > ${TESTFILE} << EOF
do_foo() {
    :
}
addtask do_compile after do_configure before do_foo
addtask do_configure after do_compile
addtask do_foo before do_configure
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) -ge "${TESTOCC}" ] && exit 0
echo "Test for ${0} failed"
exit 1