#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.autorev"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRCREV = "abcdef"
SRCREV = "\${abcdef}"
SRCREV = "AUTOREF"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1