#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pkgspecific"
TESTOCC="0"
cat > ${TESTFILE} << EOF
RDEPENDS_\${PN} = "foo"
RRECOMMENDS_\${PN} = "foo"
RSUGGESTS_\${PN} = "foo"
RCONFLICTS_\${PN} = "foo"
RPROVIDES_\${PN} = "foo"
RREPLACES_\${PN} = "foo"
FILES_\${PN} = "foo"
pkg_preinst_\${PN} = "foo"
pkg_postinst_\${PN} = "foo"
pkg_prerm_\${PN} = "foo"
pkg_postrm_\${PN} = "foo"
ALLOW_EMPTY_\${PN} = "foo"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1