#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.func.machinespecific"
TESTOCC="0"
cat > ${TESTFILE} << EOF
COMPATIBLE_MACHINE = "foo"
COMPATIBLE_MACHINE += "|bar"
do_install_append_fooarch() {
    abc
}
do_configure_append_bararch() {
    abc
}
do_install_ptest () {
 	cp -r \${B}/testsuite \${D}\${PTEST_PATH}/
 	cp \${B}/.config      \${D}\${PTEST_PATH}/
 	ln -s /bin/busybox   \${D}\${PTEST_PATH}/busybox
}
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1