#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.dependsordered"
TESTOCC="6"
cat > ${TESTFILE} << EOF
DEPENDS += "zzz \
            xyz"
DEPENDS += "foo"
DEPENDS += "bar"
RDEPENDS_\${PN} += "zzz \
            xyz"
RDEPENDS_\${PN} += "foo"
RDEPENDS_\${PN} += "bar"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1