#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.task.order"
TESTOCC="0"
cat > ${TESTFILE} << EOF
do_fetch() {
    :
}
do_unpack() {
    :
}
do_patch() {
    :
}
do_configure() {
    :
}
do_compile() {
    :
}
do_install() {
    :
}
do_populate_sysroot() {
    :
}
do_package() {
    :
}
}
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1