#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pnbpnusage"
TESTOCC="1"
cat > ${TESTFILE} << EOF
SRC_URI = "file://\${PN}.patch \
           git://\${PN}.com/\${PN}.git \
           https://foo.org/\${PN}"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1