#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.multilineident"
TESTOCC="0"
cat > ${TESTFILE} << EOF
A = "a \\
     b \\
     e \\
    "
UPSTREAM_CHECK_REGEX = "(?P<pver>12\.\d+\.\d+)"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1