#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pnbpnusage"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://\${BPN}.patch \
           git://\${BPN}.com/\${BPN}.git \
           https://foo.org/\${BPN}"
EOF
[ $(oelint-adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1