#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.notrailingslash"
TESTOCC="4"
cat > ${TESTFILE} << EOF
S = "\${WORDKIR}/foo/"
D = "\${WORDKIR}/foo/"
T = "\${WORDKIR}/foo/"
B = "\${WORDKIR}/foo/"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1