#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.suggestedvar"
TESTOCC="0"
cat > ${TESTFILE} << EOF
BUGTRACKER = "1"
BBCLASSEXTEND = "1"
CVE_PRODUCT = "1"
AUTHOR = "foo"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1