#!/bin/sh
TESTFILE="${TMP}oelint_adv_test.bbappend"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.append.protvars.*"
TESTOCC="5"
cat > ${TESTFILE} << EOF
PV = "sdlsdsd"
PR = "sdsd"
SRCREV = "ksdhdhkdhk"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = "skddskda"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1
_got=$(python3 -m oelint_adv --addrules=jetm ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1