#!/bin/sh
TESTFILE="/tmp/oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.mandatoryvar"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SUMMARY = "foo"
DESCRIPTION = "foo"
AUTHOR = "foo"
HOMEPAGE = "foo"
SECTION = "foo"
LICENSE = "foo"
SRC_URI = "foo"
EOF
[ $(python3 -m oelint_adv ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
echo "Test for ${0} failed"
exit 1