#! /usr/bin/env python3
# Copyright (c) 2024, Konrad Weihmann
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json
import tempfile
import subprocess
import os
import sys

basepath = os.path.abspath(os.path.dirname(__file__))
sys.path.append(os.path.abspath(basepath + '/../'))


def create_argparser() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument('branch', help='poky branch')
    parser.add_argument('destination')
    return parser.parse_args()


args = create_argparser()

with tempfile.TemporaryDirectory() as t:
    subprocess.run(['git', 'clone', 'https://git.yoctoproject.org/poky', '--single-branch', '-b', args.branch], cwd=t)
    output = subprocess.check_output(
        f'source poky/oe-init-build-env > /dev/null 2>&1 && {basepath}/bitbake-listvars -q $(which bitbake)',
        shell=True,
        universal_newlines=True,
        executable='/bin/bash',
        cwd=t
    )

    if args.branch == 'master':
        # for master override the name
        from oelint_adv.tweaks import Tweaks
        args.destination = os.path.join(os.path.dirname(args.destination), Tweaks.DEVELOPMENT_RELEASE + '.json')

    with open(args.destination, 'w') as o:
        obj = {'variables': {'known': [x for x in output.split('\n') if x]}}
        json.dump(obj, o, indent=2)
