name: Bump known vars

on:
  schedule:
    # Saturday 4:30am
    - cron: "30 4 * * 6"
  workflow_dispatch:

jobs:
  bumpvar:
    name: "Bump known vars"
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        # currently in support branches of oe-core
        branch: ['kirkstone', 'scarthgap', 'styhead', 'master']

    if: github.repository == 'priv-kweihmann/oelint-adv'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: |
          sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential \
               chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
               iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool \
               file locales libacl1
          sudo locale-gen en_US.UTF-8
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Bump known vars for ${{ matrix.branch }}
        run: ${GITHUB_WORKSPACE}/scripts/bump-vars ${{ matrix.branch }}
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          reviewers: priv-kweihmann
          branch: "chore/dataupdate-${{ matrix.branch }}"
          commit-message: "data/${{ matrix.branch }}: bump latest known variables"
          title: "data/${{ matrix.branch }}: bump latest known variables"
          body: "auto generated data update"
          add-paths: |
            oelint_adv/data/*.json
