name: Bump known vars

on:
  schedule:
    # Saturday 4:30am
    - cron: "30 4 * * 6"
  workflow_dispatch:

jobs:
  bumpvar:
    name: "Bump known vars"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: github.repository == 'priv-kweihmann/oelint-adv'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential \
               chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
               iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool \
               file locales libacl1
          sudo locale-gen en_US.UTF-8
      - name: Bump known vars for master
        run: ${GITHUB_WORKSPACE}/scripts/generate-variables master ${GITHUB_WORKSPACE}/oelint_adv/data/master.json
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          reviewers: priv-kweihmann
          branch: "chore/dataupdate"
          commit-message: "data: bump latest known variables"
          title: "data: bump latest known variables"
          body: "auto generated data update"
          add-paths: |
            oelint_adv/data/*.json
